profile: test

application.name: yosep-reactive-boiler-plate-kotlin-server

server:
  shutdown: graceful
  port: 20000
  logging:
    access: true

spring:
#  docker:
#    compose:
#      enabled: true                   # 테스트에서 compose-test.yml 자동 up/down
#      file: compose-test.yml          # 프로젝트 루트 기준 경로
#      lifecycle-management: start_and_stop
#      stop:
#        command: down
#      readiness:
#        wait: always                  # healthcheck 완료까지 대기 (권장)

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true         # ← 기존 스키마가 있을 때만 베이스라인 수행
    clean-disabled: false             # ← 테스트라 허용
    clean-on-validation-error: true   # ★ 검증 실패 시 clean → migrate
  # redis, r2dbc 설정은 @DynamicPropertySource에서 동적으로 설정됨
  kafka:
    # bootstrap-servers는 @DynamicPropertySource에서 동적으로 설정됨
    producer:
      client-id: "YOSEP-REACTIVE-BOILER-PLATE-KOTLIN-SERVER"
      retries: 3
      batch-size: 100
      compression-type: gzip
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 1
      properties:
        linger.ms: 50
    consumer:
      group-id: "YOSEP-REACTIVE-BOILER-PLATE-KOTLIN-SERVER"
      enable-auto-commit: false
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'
    listener:
      concurrency: 1
      ack-mode: manual_immediate
      poll-timeout: 3000
      type: single
      # Custom setting - auto startup listener
      auto-startup: false
    # Custom setting - retries
    retry:
      max-attempts: 10
      initial-interval: 1000
      multiplier: 2
      max-interval: 10000

kafka:
  topic:
    test:
      test-1: yosep-reactive-boiler-plate-kotlin-test-1

auto:
  create:
    topics:
      ena: true

feature:
  auto-init:
    circuitbreakers: false
