application.name: yosep-reactive-boiler-plate-kotlin-server

server:
  shutdown: graceful
  port: 20000
  logging:
    access: true

spring:
  flyway:
    enabled: true
    # 마이그레이션 스크립트 위치 (기본값과 동일하지만 명시)
    locations: classpath:db/migration
    # JDBC로 접속할 DB 정보 (R2DBC 아님!)
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf8&connectionTimeZone=LOCAL
    user: myuser
    password: secret
    # 선택 항목들
    baseline-on-migrate: false     # 기존 빈 스키마면 false 권장
    clean-disabled: true           # 실서버 안전장치 (원하면 false로)
  redis:
    master: redis://localhost:6379
    slave: redis://localhost:6379
  r2dbc:
    master:
      url: r2dbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf8&autoreconnect=true
      username: myuser
      password: secret
    slave:
      url: r2dbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf8&autoreconnect=true
      username: myuser
      password: secret
  kafka:
    bootstrap-servers: "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094"
    producer:
      client-id: "YOSEP-REACTIVE-BOILER-PLATE-KOTLIN-SERVER"
      retries: 3
      batch-size: 100
      compression-type: gzip
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 1
      properties:
        linger.ms: 50
    consumer:
      group-id: "YOSEP-REACTIVE-BOILER-PLATE-KOTLIN-SERVER"
      enable-auto-commit: false
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'
    listener:
      concurrency: 1
      ack-mode: manual_immediate
      poll-timeout: 3000
      type: single
      # Custom setting - auto startup listener
      auto-startup: false
    # Custom setting - retries
    retry:
      max-attempts: 10
      initial-interval: 1000
      multiplier: 2
      max-interval: 10000

kafka:
  topic:
    test:
      test-1: yosep-reactive-boiler-plate-kotlin-test-1

auto:
  create:
    topics:
      ena: true

webclient:
  external:
    connection-timeout: 60000
    response-timeout: 60000
    read-timeout: 60000
    write-timeout: 60000
    byte-cnt: 2097152  # 2 * 1024 * 1024

external:
  server:
    url: http://localhost:20003

ratelimit:
  max-limit: 100000
  min-limit: 30
  failure:
    threshold-ms: 500       # latency 임계
    n-threshold: 3          # 연속 초과 n회
    md: 0.5                 # 감속 비율
    counter-ttl-sec: 60     # 카운터 TTL